"""Adding User and Artical Table

Revision ID: 0b7f3b53d745
Revises: d3ea289ef26e
Create Date: 2023-04-25 22:01:47.579697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7f3b53d745'
down_revision = 'd3ea289ef26e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
